language: node_js
node_js:
  - 0.8
before_script:
  - psql -c 'drop database if exists test;' -U postgres
  - psql -c 'create database test;' -U postgres
  - mysql -e 'drop database if exists test;'
  - mysql -e 'create database test;'
